// calls to backend APIs go here.  If this file becomes unmanageably large,
// create a src/api/ directory.
// The API documentation for the TMBB can be found here:
// https://developers.themoviedb.org/3
let CONFIG = require('./config.json');
const baseUrl = 'https://developers.themoviedb.org/3';
const API_KEY = CONFIG.API_KEY;
const externalIdSource = 'imdb_id';
//TODO
// replace this array and the functions below with omdbapi.com calls
const MovieAPI = {
  
  movies: [
    {"Title":"The Shining","Year":"1980","Rated":"R","Released":"13 Jun 1980","Runtime":"146 min","Genre":"Drama, Horror","Director":"Stanley Kubrick","Writer":"Stephen King (novel), Stanley Kubrick (screenplay), Diane Johnson (screenplay)","Actors":"Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers","Plot":"A family heads to an isolated hotel for the winter where an evil spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future.","Language":"English","Country":"UK, USA","Awards":"3 wins & 7 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"63/100"}],"Metascore":"63","imdbRating":"8.4","imdbVotes":"689,591","imdbID":"tt0081505","Type":"movie","DVD":"29 Jun 1999","BoxOffice":"N/A","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
    {"Title":"The Social Network","Year":"2010","Rated":"PG-13","Released":"01 Oct 2010","Runtime":"120 min","Genre":"Biography, Drama","Director":"David Fincher","Writer":"Aaron Sorkin (screenplay), Ben Mezrich (book)","Actors":"Jesse Eisenberg, Rooney Mara, Bryan Barter, Dustin Fitzsimons","Plot":"Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, but is later sued by two brothers who claimed he stole their idea, and the co-founder who was later squeezed out of the business.","Language":"English, French","Country":"USA","Awards":"Won 3 Oscars. Another 165 wins & 168 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTM2ODk0NDAwMF5BMl5BanBnXkFtZTcwNTM1MDc2Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"96%"},{"Source":"Metacritic","Value":"95/100"}],"Metascore":"95","imdbRating":"7.7","imdbVotes":"525,654","imdbID":"tt1285016","Type":"movie","DVD":"11 Jan 2011","BoxOffice":"$96,400,000","Production":"Columbia Pictures","Website":"http://www.thesocialnetwork-movie.com/","Response":"True"},
    {"Title":"The Silence of the Lambs","Year":"1991","Rated":"R","Released":"14 Feb 1991","Runtime":"118 min","Genre":"Crime, Drama, Thriller","Director":"Jonathan Demme","Writer":"Thomas Harris (novel), Ted Tally (screenplay)","Actors":"Jodie Foster, Lawrence A. Bonney, Kasi Lemmons, Lawrence T. Wrentz","Plot":"A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.","Language":"English","Country":"USA","Awards":"Won 5 Oscars. Another 49 wins & 38 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"95%"},{"Source":"Metacritic","Value":"85/100"}],"Metascore":"85","imdbRating":"8.6","imdbVotes":"1,001,576","imdbID":"tt0102926","Type":"movie","DVD":"01 Jul 1998","BoxOffice":"N/A","Production":"Orion Pictures Corporation","Website":"N/A","Response":"True"},
    {"Title":"National Lampoon's Christmas Vacation","Year":"1989","Rated":"PG-13","Released":"01 Dec 1989","Runtime":"97 min","Genre":"Comedy","Director":"Jeremiah S. Chechik","Writer":"John Hughes","Actors":"Chevy Chase, Beverly D'Angelo, Juliette Lewis, Johnny Galecki","Plot":"The Griswold family's plans for a big family Christmas predictably turn into a big disaster.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMGZkMWQ2MzMtYTkxYS00OThmLWI0ZTQtNmY0ZTkyY2E4MjliXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.6/10"},{"Source":"Rotten Tomatoes","Value":"64%"},{"Source":"Metacritic","Value":"49/100"}],"Metascore":"49","imdbRating":"7.6","imdbVotes":"116,610","imdbID":"tt0097958","Type":"movie","DVD":"18 Nov 1997","BoxOffice":"N/A","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
    {"Title":"The Truman Show","Year":"1998","Rated":"PG","Released":"05 Jun 1998","Runtime":"103 min","Genre":"Comedy, Drama, Sci-Fi","Director":"Peter Weir","Writer":"Andrew Niccol","Actors":"Jim Carrey, Laura Linney, Noah Emmerich, Natascha McElhone","Plot":"An insurance salesman/adjuster discovers his entire life is actually a television show.","Language":"English","Country":"USA","Awards":"Nominated for 3 Oscars. Another 38 wins & 65 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMDIzODcyY2EtMmY2MC00ZWVlLTgwMzAtMjQwOWUyNmJjNTYyXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"90/100"}],"Metascore":"90","imdbRating":"8.1","imdbVotes":"745,209","imdbID":"tt0120382","Type":"movie","DVD":"26 Jan 1999","BoxOffice":"N/A","Production":"Paramount Pictures","Website":"N/A","Response":"True"},
    {"Title":"It","Year":"2017","Rated":"R","Released":"08 Sep 2017","Runtime":"135 min","Genre":"Horror, Thriller","Director":"Andy Muschietti","Writer":"Chase Palmer (screenplay by), Cary Fukunaga (screenplay by), Gary Dauberman (screenplay by), Stephen King (based on the novel by)","Actors":"Jaeden Lieberher, Jeremy Ray Taylor, Sophia Lillis, Finn Wolfhard","Plot":"A group of bullied kids band together when a shapeshifting monster, taking the appearance of a clown, begins hunting children.","Language":"English","Country":"USA, Canada","Awards":"1 win.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZDVkZmI0YzAtNzdjYi00ZjhhLWE1ODEtMWMzMWMzNDA0NmQ4XkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"85%"},{"Source":"Metacritic","Value":"70/100"}],"Metascore":"70","imdbRating":"7.7","imdbVotes":"182,545","imdbID":"tt1396484","Type":"movie","DVD":"19 Dec 2017","BoxOffice":"$326,898,358","Production":"Warner Bros. Pictures","Website":"http://www.Itthemovie.com","Response":"True"},
    {"Title":"Alien","Year":"1979","Rated":"R","Released":"22 Jun 1979","Runtime":"117 min","Genre":"Horror, Sci-Fi","Director":"Ridley Scott","Writer":"Dan O'Bannon (story), Ronald Shusett (story), Dan O'Bannon (screenplay)","Actors":"Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton","Plot":"After a space merchant vessel perceives an unknown transmission as a distress call, its landing on the source moon finds one of the crew attacked by a mysterious lifeform, and they soon realize that its life cycle has merely begun.","Language":"English","Country":"UK, USA","Awards":"Won 1 Oscar. Another 16 wins & 19 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNDNhN2IxZWItNGEwYS00ZDNhLThiM2UtODU3NWJlZjBkYjQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"97%"},{"Source":"Metacritic","Value":"83/100"}],"Metascore":"83","imdbRating":"8.5","imdbVotes":"640,992","imdbID":"tt0078748","Type":"movie","DVD":"06 Jan 2004","BoxOffice":"N/A","Production":"20th Century Fox","Website":"http://www.foxmovies.com/index1.html","Response":"True"},
    {"Title":"The Revenant","Year":"2015","Rated":"R","Released":"08 Jan 2016","Runtime":"156 min","Genre":"Adventure, Drama, History","Director":"Alejandro González Iñárritu","Writer":"Mark L. Smith (screenplay), Alejandro González Iñárritu (screenplay), Michael Punke (based in part on the novel by)","Actors":"Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson, Will Poulter","Plot":"A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.","Language":"English, Pawnee, French","Country":"USA, Hong Kong, Taiwan","Awards":"Won 3 Oscars. Another 86 wins & 181 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BY2FmODc2N2QtYmY3MS00YTMwLWI2NGYtZWRmYWVkNjFjZmI0XkEyXkFqcGdeQXVyNTMxMjgxMzA@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"80%"},{"Source":"Metacritic","Value":"76/100"}],"Metascore":"76","imdbRating":"8.0","imdbVotes":"530,991","imdbID":"tt1663202","Type":"movie","DVD":"19 Apr 2016","BoxOffice":"N/A","Production":"20th Century Fox","Website":"http://www.foxmovies.com/movies/the-revenant","Response":"True"},
    {"Title":"The Dark Knight","Year":"2008","Rated":"PG-13","Released":"18 Jul 2008","Runtime":"152 min","Genre":"Action, Crime, Drama","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)","Actors":"Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine","Plot":"When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham, the Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.","Language":"English, Mandarin","Country":"USA, UK","Awards":"Won 2 Oscars. Another 151 wins & 154 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"9.0/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"82/100"}],"Metascore":"82","imdbRating":"9.0","imdbVotes":"1,859,803","imdbID":"tt0468569","Type":"movie","DVD":"09 Dec 2008","BoxOffice":"$533,316,061","Production":"Warner Bros. Pictures/Legendary","Website":"http://thedarkknight.warnerbros.com/","Response":"True"},
    {"Title":"Inception","Year":"2010","Rated":"PG-13","Released":"16 Jul 2010","Runtime":"148 min","Genre":"Action, Adventure, Sci-Fi","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy","Plot":"A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.","Language":"English, Japanese, French","Country":"USA, UK","Awards":"Won 4 Oscars. Another 152 wins & 204 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.8/10"},{"Source":"Rotten Tomatoes","Value":"86%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"8.8","imdbVotes":"1,645,994","imdbID":"tt1375666","Type":"movie","DVD":"07 Dec 2010","BoxOffice":"$292,568,851","Production":"Warner Bros. Pictures","Website":"http://inceptionmovie.warnerbros.com/","Response":"True"},
    {"Title":"Die Hard","Year":"1988","Rated":"R","Released":"20 Jul 1988","Runtime":"132 min","Genre":"Action, Thriller","Director":"John McTiernan","Writer":"Roderick Thorp (novel), Jeb Stuart (screenplay), Steven E. de Souza (screenplay)","Actors":"Bruce Willis, Bonnie Bedelia, Reginald VelJohnson, Paul Gleason","Plot":"John McClane, officer of the NYPD, tries to save his wife Holly Gennaro and several others that were taken hostage by German terrorist Hans Gruber during a Christmas party at the Nakatomi Plaza in Los Angeles.","Language":"English, German, Italian","Country":"USA","Awards":"Nominated for 4 Oscars. Another 6 wins & 2 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMzNmY2IwYzAtNDQ1NC00MmI4LThkOTgtZmVhYmExOTVhMWRkXkEyXkFqcGdeQXVyMTk5NDA3Nw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.2/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"70/100"}],"Metascore":"70","imdbRating":"8.2","imdbVotes":"654,634","imdbID":"tt0095016","Type":"movie","DVD":"09 Mar 1999","BoxOffice":"N/A","Production":"20th Century Fox","Website":"http://www.foxhome.com/diehardcollection/index_frames.html","Response":"True"},
    {"Title":"North by Northwest","Year":"1959","Rated":"NOT RATED","Released":"26 Sep 1959","Runtime":"136 min","Genre":"Action, Adventure, Mystery","Director":"Alfred Hitchcock","Writer":"Ernest Lehman","Actors":"Cary Grant, Eva Marie Saint, James Mason, Jessie Royce Landis","Plot":"A hapless New York advertising executive is mistaken for a government agent by a group of foreign spies, and is pursued across the country while he looks for a way to survive.","Language":"English","Country":"USA","Awards":"Nominated for 3 Oscars. Another 8 wins & 4 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZDA3NDExMTUtMDlhOC00MmQ5LWExZGUtYmI1NGVlZWI4OWNiXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.4/10"},{"Source":"Rotten Tomatoes","Value":"100%"}],"Metascore":"N/A","imdbRating":"8.4","imdbVotes":"243,185","imdbID":"tt0053125","Type":"movie","DVD":"29 Aug 2000","BoxOffice":"N/A","Production":"Turner Entertainment","Website":"N/A","Response":"True"},
    {"Title":"The Fifth Element","Year":"1997","Rated":"PG-13","Released":"09 May 1997","Runtime":"126 min","Genre":"Action, Adventure, Sci-Fi","Director":"Luc Besson","Writer":"Luc Besson (screenplay by), Robert Mark Kamen (screenplay by), Luc Besson (story by)","Actors":"Bruce Willis, Gary Oldman, Ian Holm, Milla Jovovich","Plot":"In the colorful future, a cab driver unwittingly becomes the central figure in the search for a legendary cosmic weapon to keep Evil and Mr. Zorg at bay.","Language":"English, Swedish, German","Country":"France","Awards":"Nominated for 1 Oscar. Another 9 wins & 36 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZWFjYmZmZGQtYzg4YS00ZGE5LTgwYzAtZmQwZjQ2NDliMGVmXkEyXkFqcGdeQXVyNTUyMzE4Mzg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"72%"},{"Source":"Metacritic","Value":"52/100"}],"Metascore":"52","imdbRating":"7.7","imdbVotes":"373,770","imdbID":"tt0119116","Type":"movie","DVD":"09 Dec 1997","BoxOffice":"N/A","Production":"Sony Pictures Home Entertainment","Website":"N/A","Response":"True"},
    {"Title":"Get Out","Year":"2017","Rated":"R","Released":"24 Feb 2017","Runtime":"104 min","Genre":"Horror, Mystery, Thriller","Director":"Jordan Peele","Writer":"Jordan Peele","Actors":"Daniel Kaluuya, Allison Williams, Catherine Keener, Bradley Whitford","Plot":"It's time for a young African American to meet with his white girlfriend's parents for a weekend in their secluded estate in the woods, but before long, the friendly and polite ambience will give way to a nightmare.","Language":"English","Country":"USA","Awards":"4 wins & 24 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTBhMjVkNGYtYTZhOS00YjYwLWJhOGItOWZiMjAwYzQ0ZTQzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.7/10"},{"Source":"Rotten Tomatoes","Value":"99%"},{"Source":"Metacritic","Value":"84/100"}],"Metascore":"84","imdbRating":"7.7","imdbVotes":"197,130","imdbID":"tt5052448","Type":"movie","DVD":"23 May 2017","BoxOffice":"$175,428,355","Production":"Universal Pictures","Website":"http://www.getoutfilm.com/","Response":"True"},
    {"Title":"The Prestige","Year":"2006","Rated":"PG-13","Released":"20 Oct 2006","Runtime":"130 min","Genre":"Drama, Mystery, Sci-Fi","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Priest (novel)","Actors":"Hugh Jackman, Christian Bale, Michael Caine, Piper Perabo","Plot":"After a tragic accident two stage magicians engage in a battle to create the ultimate illusion whilst sacrificing everything they have to outwit the other.","Language":"English","Country":"USA, UK","Awards":"Nominated for 2 Oscars. Another 5 wins & 36 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.5/10"},{"Source":"Rotten Tomatoes","Value":"75%"},{"Source":"Metacritic","Value":"66/100"}],"Metascore":"66","imdbRating":"8.5","imdbVotes":"951,885","imdbID":"tt0482571","Type":"movie","DVD":"20 Feb 2007","BoxOffice":"$53,100,000","Production":"Buena Vista Pictures","Website":"http://touchstone.movies.go.com/index.html?dlink=prestige","Response":"True"},
    {"Title":"Little Miss Sunshine","Year":"2006","Rated":"R","Released":"18 Aug 2006","Runtime":"101 min","Genre":"Comedy, Drama","Director":"Jonathan Dayton, Valerie Faris","Writer":"Michael Arndt","Actors":"Abigail Breslin, Greg Kinnear, Paul Dano, Alan Arkin","Plot":"A family determined to get their young daughter into the finals of a beauty pageant take a cross-country trip in their VW bus.","Language":"English","Country":"USA","Awards":"Won 2 Oscars. Another 68 wins & 107 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTgzNTgzODU0NV5BMl5BanBnXkFtZTcwMjEyMjMzMQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.8/10"},{"Source":"Rotten Tomatoes","Value":"91%"},{"Source":"Metacritic","Value":"80/100"}],"Metascore":"80","imdbRating":"7.8","imdbVotes":"383,889","imdbID":"tt0449059","Type":"movie","DVD":"19 Dec 2006","BoxOffice":"$59,831,476","Production":"Fox Searchlight","Website":"http://www2.foxsearchlight.com/littlemisssunshine/","Response":"True"},
    {"Title":"Birdman or (The Unexpected Virtue of Ignorance)","Year":"2014","Rated":"R","Released":"14 Nov 2014","Runtime":"119 min","Genre":"Comedy, Drama","Director":"Alejandro G. Iñárritu","Writer":"Alejandro G. Iñárritu, Nicolás Giacobone, Alexander Dinelaris, Armando Bo, Raymond Carver (play)","Actors":"Michael Keaton, Emma Stone, Kenny Chin, Jamahl Garrison-Lowe","Plot":"A washed-up actor, who once played an iconic superhero, attempts to revive his career by writing and starring in a Broadway play.","Language":"English","Country":"USA","Awards":"Won 4 Oscars. Another 191 wins & 275 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BODAzNDMxMzAxOV5BMl5BanBnXkFtZTgwMDMxMjA4MjE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.8/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"88/100"}],"Metascore":"88","imdbRating":"7.8","imdbVotes":"462,726","imdbID":"tt2562232","Type":"movie","DVD":"17 Feb 2015","BoxOffice":"N/A","Production":"Fox Searchlight","Website":"http://www.birdmanthemovie.com/","Response":"True"}

  ],

  genres: {
    "genres": [
     {"id": 1,"name": "Action"},
     {"id": 2,"name": "Comedy"},
     {"id": 3,"name": "Sci-Fi"},
     {"id": 4,"name": "Drama"},
     {"id": 5,"name": "Thriller"},
     {"id": 6,"name": "Horror"},
     {"id": 7,"name": "Mystery"}
    ]
  },

 /**
   * Get a single movie by movie_id.
   * @param {*} movie_id - the IMDB movie id.
   */
  getMovieById: function(movie_id) {
    // gets mock data from the movies[] array
    const isMovie = m => m.imdbID === movie_id;
    return this.movies.find(isMovie);
    // fetch(`${baseUrl}/find/${movie_id}?api_key=${API_KEY}&external_source=${externalIdSource}`)
    //   .then(results => {
    //     return results.json();
    //   });
  },

  /**
   * Get a list of movies returned by the search term.
   * @param {*} num - get the first num movies from the movies[] array.
   */
  getMovies: function(num) {
    // gets mock data from the movies[] array
    return this.movies.slice(0, num);
    //
    // this should maybe update state?
  },

  /**
   * Returns num movies by key using the string value: object['key'].
   * @param {*} key - key to search for
   * @param {*} val - val to search key for
   * @param {*} num - number of movies to return
   */
  getMoviesByKeyVal: function(key, val, num) {
    return this.movies.filter((movie) => 
      movie[key].toLowerCase().indexOf(val.toLowerCase()) >  -1
    ).slice(0, num);
  },

  /**
   * Get a list of genres.
   */
  getGenres: function() {
    // gets mock data from the genres object
    return this.genres;
  }
}

export default MovieAPI;